services:
  postgres:
    container_name: postgres
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql
      # - ./database/postgresql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./database/postgresql/pg_hba.conf:/etc/postgresql/common/pg_hba.conf

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "${PGADMIN_PORT}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "${SERVER_PORT}:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}

  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        REACT_APP_CAPTCHA_API_KEY: ${CAPTCHA_API_KEY}
    ports:
      - "${CLIENT_PORT}:3000"
    depends_on:
      - server
    environment:
      REACT_APP_CAPTCHA_API_KEY: ${CAPTCHA_API_KEY}

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "${PROXY_PORT}:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./client/build:/usr/share/nginx/html
    depends_on:
      - client
      - server

volumes:
  postgres_data:
  pgadmin_data:
